Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The vpcID where the security group will be created. Hello world!!
  SecurityGroupName:
    Type: String
    Description: Name of the security group to be created
  
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EIAM project (EC2)
      GroupName: !Ref SecurityGroupName
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          ToPort: 443
          IpProtocol: TCP
      Tags:
        - Value: !Ref SecurityGroupName
          Key: HolaCarlos^2!!
